/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.buddycloud.android.buddydroid;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int background=0x7f060001;
        public static final int lightningbg=0x7f060000;
        public static final int textcolor=0x7f060002;
    }
    public static final class drawable {
        public static final int add_channel_msg=0x7f020000;
        public static final int buddycloud_2=0x7f020001;
        public static final int channel=0x7f020002;
        public static final int channel_view_add_msg=0x7f020003;
        public static final int channel_view_background=0x7f020004;
        public static final int channel_view_msg_background=0x7f020005;
        public static final int channel_view_msg_bottom_background=0x7f020006;
        public static final int channel_view_msg_top_background=0x7f020007;
        public static final int contact=0x7f020008;
        public static final int down_right=0x7f020009;
        public static final int history1=0x7f02000a;
        public static final int history2=0x7f02000b;
        public static final int ic_input_add=0x7f02000c;
        public static final int ic_input_add_24=0x7f02000d;
        public static final int ic_input_add_32=0x7f02000e;
        public static final int ic_menu_allfriends=0x7f02000f;
        public static final int ic_menu_friendslist=0x7f020010;
        public static final int ic_menu_stop=0x7f020011;
        public static final int icon=0x7f020012;
        public static final int icon_statusbar=0x7f020013;
        public static final int lightdialogbg=0x7f020014;
        public static final int message_star=0x7f020015;
        public static final int place=0x7f020016;
        public static final int up_right=0x7f020017;
    }
    public static final class id {
        public static final int Button01=0x7f0a002f;
        public static final int LinearLayout01=0x7f0a0003;
        public static final int LinearLayout02=0x7f0a002d;
        public static final int ScrollView01=0x7f0a001b;
        public static final int abort=0x7f0a0004;
        public static final int add_icon=0x7f0a002b;
        public static final int anonymousButton=0x7f0a0020;
        public static final int anonymous_login_text=0x7f0a001f;
        public static final int bottom_shadow=0x7f0a000d;
        public static final int channel_jid=0x7f0a0007;
        public static final int channel_row=0x7f0a0027;
        public static final int channel_title=0x7f0a0006;
        public static final int currentlyLocated=0x7f0a002e;
        public static final int description=0x7f0a0026;
        public static final int e_mail_text=0x7f0a0016;
        public static final int e_mail_textbox=0x7f0a0017;
        public static final int edit=0x7f0a0002;
        public static final int exit_button=0x7f0a0023;
        public static final int feedback=0x7f0a003a;
        public static final int follow=0x7f0a000e;
        public static final int goto_login_button=0x7f0a0022;
        public static final int icon=0x7f0a0031;
        public static final int jid=0x7f0a0029;
        public static final int layout_root=0x7f0a0000;
        public static final int list=0x7f0a0024;
        public static final int loc_current=0x7f0a0010;
        public static final int loc_next=0x7f0a0015;
        public static final int loc_next_icon=0x7f0a0014;
        public static final int loc_prev=0x7f0a0012;
        public static final int loc_prev_icon=0x7f0a0013;
        public static final int loc_prev_next_container=0x7f0a0011;
        public static final int location=0x7f0a002a;
        public static final int location_container=0x7f0a000f;
        public static final int login_button=0x7f0a001a;
        public static final int login_text=0x7f0a0021;
        public static final int message=0x7f0a002c;
        public static final int message_container=0x7f0a000a;
        public static final int message_inline_container=0x7f0a000b;
        public static final int message_list=0x7f0a0008;
        public static final int mood=0x7f0a0037;
        public static final int open_channel=0x7f0a003c;
        public static final int orig=0x7f0a0001;
        public static final int password_text=0x7f0a0018;
        public static final int password_textbox=0x7f0a0019;
        public static final int placeName=0x7f0a0032;
        public static final int placeStreetLocation=0x7f0a0033;
        public static final int placesList=0x7f0a0030;
        public static final int post=0x7f0a0005;
        public static final int post_message=0x7f0a0034;
        public static final int posting=0x7f0a0035;
        public static final int roster_list=0x7f0a0036;
        public static final int settings=0x7f0a0039;
        public static final int star=0x7f0a0038;
        public static final int stop=0x7f0a003b;
        public static final int textview1=0x7f0a001c;
        public static final int textview2=0x7f0a001d;
        public static final int textview3=0x7f0a001e;
        public static final int title=0x7f0a0025;
        public static final int top_shadow=0x7f0a0009;
        public static final int user_icon=0x7f0a0028;
        public static final int webimage=0x7f0a000c;
    }
    public static final class layout {
        public static final int add_channel_msg=0x7f030000;
        public static final int channel_layout=0x7f030001;
        public static final int channel_row=0x7f030002;
        public static final int follow=0x7f030003;
        public static final int location_fragment=0x7f030004;
        public static final int login=0x7f030005;
        public static final int main=0x7f030006;
        public static final int main_start=0x7f030007;
        public static final int nearby=0x7f030008;
        public static final int nearby_row=0x7f030009;
        public static final int personal_post_fragment=0x7f03000a;
        public static final int places=0x7f03000b;
        public static final int places_row=0x7f03000c;
        public static final int post_message=0x7f03000d;
        public static final int roster=0x7f03000e;
        public static final int roster_row=0x7f03000f;
    }
    public static final class menu {
        public static final int main=0x7f090000;
        public static final int roster_context=0x7f090001;
    }
    public static final class raw {
        public static final int cp=0x7f050000;
        public static final int dr=0x7f050001;
        public static final int pm=0x7f050002;
    }
    public static final class string {
        public static final int anonymous_text=0x7f070005;
        public static final int app_follow_name=0x7f070001;
        public static final int app_login_name=0x7f070004;
        public static final int app_name=0x7f070000;
        public static final int app_post_name=0x7f070002;
        public static final int main_title=0x7f070003;
        public static final int normal_login_text=0x7f070006;
        public static final int places_add_bookmark=0x7f070008;
        public static final int places_current=0x7f070007;
    }
    public static final class style {
        public static final int MyDialog=0x7f080001;
        public static final int MyOverlayDialog=0x7f080002;
        public static final int MyTheme=0x7f080000;
    }
    public static final class xml {
        public static final int settings=0x7f040000;
    }
}
